<?php

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use App\Models\Lead;

class LeadsTableSeeder extends Seeder
{
	public function run()
	{
		Lead::truncate();

		$faker = Faker::create();
		$save_date = date('Y-m-d H:i:s');

		$leads = [
			['position' => 1, 'lead_owner' => 1, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(1, 4), 'company' => $faker->company, 'first_name' => 'John', 'last_name' => 'Doe', 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => null, 'converted_contact_id' => null, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' => 2, 'lead_owner' => 1, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(1, 4), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => null, 'converted_contact_id' => null, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' => 3, 'lead_owner' => 2, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(1, 4), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => null, 'converted_contact_id' => null, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' => 4, 'lead_owner' => 2, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(1, 4), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => null, 'converted_contact_id' => null, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' => 5, 'lead_owner' => 3, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(1, 4), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => null, 'converted_contact_id' => null, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' => 6, 'lead_owner' => 3, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(1, 4), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => null, 'converted_contact_id' => null, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' => 7, 'lead_owner' => 4, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(5, 5), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => 1, 'converted_contact_id' => 1, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' => 8, 'lead_owner' => 4, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(5, 5), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => 2, 'converted_contact_id' => 2, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' => 9, 'lead_owner' => 5, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(6, 7), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'private', 'description' => $faker->text(200), 'converted_account_id' => null, 'converted_contact_id' => null, 'created_at' => $save_date, 'updated_at' => $save_date],
			['position' =>10, 'lead_owner' => 5, 'source_id' => rand(1, 10), 'lead_stage_id' => rand(6, 7), 'company' => $faker->company, 'first_name' => $faker->firstName, 'last_name' => $faker->lastName, 'date_of_birth' => $faker->dateTimeThisCentury->format('Y-m-d'), 'title' => $faker->jobTitle, 'email' => $faker->freeEmail, 'phone' => $faker->phoneNumber, 'timezone' => config('app.timezone'), 'fax' => rand(31937729, 51937729), 'website' => 'www.'.$faker->domainName, 'no_of_employees' => rand(50, 1000), 'currency_id' => 1, 'annual_revenue' => rand(1000000, 9999999), 'street' => $faker->streetAddress, 'city' => $faker->city, 'state' => $faker->state, 'zip' => $faker->postcode, 'country_code' => $faker->countryCode, 'access' => 'public', 'description' => $faker->text(200), 'converted_account_id' => null, 'converted_contact_id' => null, 'created_at' => $save_date, 'updated_at' => $save_date]
		];

		Lead::insert($leads);
	}
}